### ISSUE TITLE
Docker builds failing with Docker driver error

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/sqlfmt#372]
Our [build action](https://github.com/tconbeer/sqlfmt/actions/runs/3989166465/jobs/6841263509) is failing with:

```
Error: buildx failed with: ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

**Comment by tconbeer** [comment]
@ysmilda FYI

**Comment by ysmilda** [comment]
I see, in the project I copied it from we have these two additional steps:
```yaml
- name: Set up QEMU
  uses: docker/setup-qemu-action@v2

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
```

Wasn't sure they're related to those platforms, but it seems they are.
