### ISSUE TITLE
Flag -k/--reset-cache does not work in a pre-commit hook

### ISSUE THREAD

**Issue by ivan-toriya-precis** [tconbeer/sqlfmt#397]
**Describe the bug**
Flag -k/--reset-cache does not work in a pre-commit hook.

**To Reproduce**
I don't know how to reproduce the state when it's passing all the checks when --reset-cache not used, but fails when the --reset-cache is used. For me it happened somewhere after I changed/created a file, committed it and pre-commit hook run automatically and passed (having --reset-cache), but then it failed in CI/CD pipeline where --reset-cache flag is working properly. 

**Expected behavior**
Flag -k/--reset-cache does should work in a pre-commit hook.

**Actual behavior**

.pre-commit-config.yaml
```
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.17.0
    hooks:
      - id: sqlfmt
        name: Format SQL
        description: Format SQL using sqlfmt
        entry: sqlfmt
        args:
          - --check
          - --reset-cache
          - dbt_projects
        language_version: python3.9
```

```
> sqlfmt --check dbt_projects
174 files passed formatting check.
```
```
> sqlfmt --check dbt_projects --reset-cache
1 file failed formatting check.
173 files passed formatting check.
dbt_projects/[...].sql failed formatting check.
```
```
> pre-commit run --all -v
Format SQL...............................................................Passed
- hook id: sqlfmt
- duration: 1.96s

174 files passed formatting check. 
```

**Additional context**
What is the output of `sqlfmt --version`?
`sqlfmt, version 0.17.0`
