### ISSUE TITLE
`<=>` operator not getting formatted correctly

### ISSUE THREAD

**Issue by kathykwon** [tconbeer/sqlfmt#432]
**Describe the bug**
The `<=>` operator is not getting formatted correctly.

**To Reproduce**
```
select * from foo join bar on foo.baz <=> bar.baz
```

**Expected behavior**
```
select * from foo join bar on foo.baz <=> bar.baz
```

**Actual behavior**
```
select * from foo join bar on foo.baz <= > bar.baz
```

**Additional context**
 Running v0.18.0 on a pre-commit hook.
```
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.18.0
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: [".[jinjafmt]"]
```
