### ISSUE TITLE
Sqlfmt output differs between Github Actions and local runs and fails GHA

### ISSUE THREAD

**Issue by omarabed15** [tconbeer/sqlfmt#464]
**Describe the bug**
When I run sqlfmt locally, using python 3.10 and sqlfmt v0.19.X, I am getting slightly different output than when I run sqlfmt through a Github Action (GHA) using the same versions. This is causing my Github Action step to fail every time on the sqlfmt runner step.
The main issues tend to be that quoted text is getting set as single-quote (`'`) locally, but double quotes (`"`) in the Github Action. I'm not sure why this would happen, and was hoping to get some clarification on which is the intended format in different versions of sqlfmt and Python. 

**To Reproduce**
Here is the config file for our Github Action. It shows that we are running on Python 3.10 and the latest version of sqlfmt:
```
name: Run sqlfmt

on:
  pull_request:
    branches:
      - master

jobs:
  static:
    name: sqlfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install sqlfmt
        run: pip install shandy-sqlfmt[jinjafmt]
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: Run sqlfmt
        run: sqlfmt --diff ${{ steps.changed-files.outputs.all_changed_files }}
```
This produces a diff suggesting double quotes.

However, when I run sqlfmt locally on the same set of files, using Python 3.10.X and sqlfmt 0.19.X, I get formatted sql with single quotes.

**Expected behavior**
I expect sqlfmt to consistently use either single or double quotes in version 0.19.X, and hope to understand which one is intended.

**Actual behavior**
I am getting double quotes (") when running sqlfmt in GHA and single quotes (') when I run sqlfmt locally, both with Python 3.10.X and sqlfmt v0.19.X. This causes my Github Action to fail.

**Additional context**
What is the output of `sqlfmt --version`?
Locally and in Github Action: 0.19.2

Python version is 3.10.12 on Github action, and I temporarily upgraded to 3.10.12 locally to test it with sqlfmt and continued to receive the single quotes locally.
