### ISSUE TITLE
`black` dependency not installed via `pip`

### ISSUE THREAD

**Issue by ljhopkins2** [tconbeer/sqlfmt#98]
### Issue

When doing a first-time, fresh install of `sqlfmt`, I get a `ModuleNotFoundError` for `black`.

I added `shandy-sqlfmt==0.4.2` to the `requirements.txt` in my dbt project, and—in a clean virtualenv—ran `pip install -r requirements.txt`.

(I know the recommended install method is `pipx`, but since `pip` is given as an option, I figured I'd log this FWIW.)

### Workaround:
- `pip install black` in the virtualenv
- Add the following `additional_dependencies` line to `.pre-commit-config.yaml`:
```
- repo: https://github.com/tconbeer/sqlfmt
  rev: v0.4.2
  hooks:
    - id: sqlfmt
      language_version: python
      additional_dependencies: ['black']
      args: [--line-length=90]
```

`sqlfmt` works 👍
